// <auto-generated />
namespace GYMdoJime2_Modulo17E.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Batatas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Batatas));
        
        string IMigrationMetadata.Id
        {
            get { return "202303211426389_Batatas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
